baseURL = 'https://isoul.uk/'
locale = 'en-GB'
defaultContentLanguage = 'en'
title = 'isoul.uk'
theme = 'blowfish'
enableRobotsTXT = true

[params]
  description = 'Keep it simple. Keep it local. Keep a copy.'
  mainSections = ['posts', 'off-the-stack', 'media']
  colorScheme = 'ocean'
  defaultAppearance = 'light'
  autoSwitchAppearance = true
  enableSearch = true
  enableCodeCopy = true
  enableStructuredBreadcrumbs = true
  disableTextInHeader = false

  [params.header]
    layout = 'floating'
    mobileMenuStyle = 'dropdown'

  [params.footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = 'page'
    showRecent = true
    showRecentItems = 9
    showMoreLink = true
    showMoreLinkDest = '/posts/'
    cardView = true
    cardViewScreenWidth = false

  [params.article]
    showDate = true
    showDateUpdated = true
    showAuthor = false
    showHero = false
    showBreadcrumbs = true
    showDraftLabel = true
    showHeadingAnchors = true
    showPagination = true
    showReadingTime = true
    showReadingProgress = true
    showTableOfContents = true
    showTaxonomies = true
    showCategories = true
    showTags = true
    showWordCount = false
    showComments = true
    sharingLinks = []

  [params.list]
    showHero = false
    showBreadcrumbs = true
    showSummary = true
    showCards = true
    groupByYear = false
    cardView = true
    cardViewScreenWidth = false
    constrainItemsWidth = false

  [params.taxonomy]
    showTermCount = true
    showBreadcrumbs = true
    cardView = true

  [params.term]
    showBreadcrumbs = true
    groupByYear = false
    cardView = true

[services.disqus]
  shortname = 'isoul-1'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[menu]
  [[menu.main]]
    name = 'Notes'
    pageRef = '/posts'
    weight = 10
  [[menu.main]]
    name = 'Off the stack'
    pageRef = '/off-the-stack'
    weight = 15
  [[menu.main]]
    name = 'Media'
    pageRef = '/media'
    weight = 17
  [[menu.main]]
    name = 'Discover'
    identifier = "discover"
    url = "/discover/"
    weight = 18
  [[menu.main]]
    name = 'App shelf'
    pageRef = '/app-shelf'
    weight = 20
  [[menu.main]]
    name = 'What’s new'
    pageRef = '/watchlist'
    weight = 30
  [[menu.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40
  [[menu.main]]
    name = 'Resources'
    pageRef = '/resources'
    weight = 50
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 60

  [[menu.footer]]
    name = 'Support iSoul'
    url = 'https://buymeacoffee.com/isoul'
    title = 'Support iSoul on Buy Me a Coffee'
    weight = 10

[markup.goldmark.renderer]
  unsafe = false

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
