baseURL = 'https://isoul.uk/'
languageCode = 'en-gb'
title = 'isoul.uk'
theme = 'PaperMod'

[params]
  env = 'production'
  title = 'isoul.uk'
  description = 'Keep it simple. Keep it local. Keep a copy.'
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowFullTextinRSS = true
  hidemeta = false
  hideSummary = false
  ShowToc = true
  TocOpen = false
  homeInfoParams = { Title = 'Keep it yours.', Content = 'Practical writing about digital ownership, preservation, selective self-hosting and the technology that shaped me.' }
[outputs]
  home = ['HTML', 'RSS', 'JSON']

[menu]
  [[menu.main]]
    name = 'Notes'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    name = 'Off the stack'
    url = '/off-the-stack/'
    weight = 15
  [[menu.main]]
    name = 'App shelf'
    url = '/app-shelf/'
    weight = 20
  [[menu.main]]
    name = 'What’s new'
    url = '/watchlist/'
    weight = 30
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 40
  [[menu.main]]
    name = 'Resources'
    url = '/resources/'
    weight = 50
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 60

[markup.goldmark.renderer]
  unsafe = false

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
